### ISSUE TITLE
Integration with Napalm-Ansible

### ISSUE THREAD

**Issue by barte91** [napalm-automation-community/napalm-s350#2]
Hi,

I want to import this driver with napalm-ansible but I have always the error "" s350 os not supported".
I set the variable ansible_connection=network_cli

Has anyone already tried this integration?

**Comment by cspeidel** [comment]
@barte91 How did you install the s350 driver?  

Ensure your napalm installation is working:
```
napalm --debug --user myusername --password mypassword --vendor s350 mydevice call get_facts  
```
Example how to get config:

```
- hosts: sg
  connection: local  
  gather_facts: no  
  tasks:  
    - name: get config from sg devices  
      napalm_get_facts:  
        hostname: switch-hostname  
        dev_os: s350  
        username: myusername  	
        password: mypassword  
        filter: 'config'  
      register: result
```
