### ISSUE TITLE
Support for CBS350-48T-4G and|or CBS250-48T-4G

### ISSUE THREAD

**Issue by pantaras** [napalm-automation-community/napalm-s350#75]
### Short description
Hello, 
Does anybody has the information whether these 2 models are/will be supported CBS350-48T-4G,  CBS250-48T-4G

I'm primary interested in "napalm_install_config" function or similar alternative. 
My current use case is for cisco2960 switches is: 
```
 tasks:
 - name: Push Config Changes
     napalm_install_config: 
            dev_os: ios
```
Really appreciate the answer
